### ISSUE TITLE
Metadata packet returning internal error

### ISSUE THREAD

**Issue by AmazinAxel** [Ekpoa/PoaSkRewritev2#7]
Setting the metadata packet of a fake player returns an internal error

Example code:
```vb
command /spawnSleeper:
    trigger:
        remove fake player named player's name for all players
        spawn fake player named player's name with skin named player's name on tablist false at player for all players
        set {_id} to entity id of fake player named player's name

        # these do not work
        send metadata packet with entity id {_id} name visible false to all players
        send metadata packet with entity id {_id} pose "sleeping" to all players
```
Errror:
![image](https://github.com/Ekpoa/PoaSkRewritev2/assets/87440159/eb1144f5-191d-4fa1-9d01-9a1e93168e73)

**Comment by Ekpoa** [comment]
try with the building one

``
set {_m} to metadata packet with id {_id}
add data from "name visible false" to {_m}
add data from "pose sleeping" to {_m}

send packet {_m} to all players
``

**Comment by AmazinAxel** [comment]
Updated the code using your method:
```vb
command /spawnSleeper:
    trigger:
        remove fake player named player's name for all players
        spawn fake player named player's name with skin named player's name on tablist false at player for all players
        set {_id} to entity id of fake player named player's name

        set {_m} to metadata packet with id {_id}
        add data from "name visible false" to {_m}
        add data from "pose sleeping" to {_m}

        send packet {_m} to all players
```
This kicked me from the game with this error:
![image](https://github.com/Ekpoa/PoaSkRewritev2/assets/87440159/a67e301e-64be-4540-ba3f-2389253be8c1)

It also logged the console with this error:
```[16:22:39 INFO]: AmazinAxel issued server command: /spawnsleeper
[16:22:39 ERROR]: #!#! 
[16:22:39 ERROR]: #!#! [Skript] Severe Error:
[16:22:39 ERROR]: #!#! 
[16:22:39 ERROR]: #!#! Something went horribly wrong with Skript.
[16:22:39 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:22:39 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[16:22:39 ERROR]: #!#! Here is full list of them:
[16:22:39 ERROR]: #!#! skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect) SkBee v3.5.1 (https://github.com/ShaneBeee/SkBee) 
[16:22:39 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[16:22:39 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[16:22:39 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[16:22:39 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[16:22:39 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[16:22:39 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[16:22:39 ERROR]: #!#! 
[16:22:39 ERROR]: #!#! Stack trace:
[16:22:39 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Iterator.next()" is null
[16:22:39 ERROR]: #!#!     at it.unimi.dsi.fastutil.ints.AbstractIntList.addAll(AbstractIntList.java:120)
[16:22:39 ERROR]: #!#!     at it.unimi.dsi.fastutil.ints.AbstractIntList.addAll(AbstractIntList.java:132)
[16:22:39 ERROR]: #!#!     at PoaSK (2).jar//poa.packets.FakeEntity1206.removeFakeEntityPacket(FakeEntity1206.java:60)
[16:22:39 ERROR]: #!#!     at PoaSK (2).jar//poa.packets.FakePlayer1206.removeFakePlayerPacket(FakePlayer1206.java:109)
[16:22:39 ERROR]: #!#!     at PoaSK (2).jar//poa.packets.FakePlayer.removeFakePlayerPacket(FakePlayer.java:36)
[16:22:39 ERROR]: Error sending packet clientbound/minecraft:player_info_remove (skippable? false)
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:player_info_remove'
	at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:53) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:20) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:26) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:12) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at net.minecraft.network.Connection$2.write(Connection.java:750) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at PoaSK (2).jar/poa.packets.packetListener.PacketHandler1206.write(PacketHandler1206.java:129) ~[PoaSK (2).jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at ProtocolLib (7).jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib (7).jar:?]
	at ProtocolLib (7).jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib (7).jar:?]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:505) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:490) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at ProtocolLib (7).jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib (7).jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.UUID.getMostSignificantBits()" because "uuid" is null
	at net.minecraft.network.FriendlyByteBuf.writeUUID(FriendlyByteBuf.java:525) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.core.UUIDUtil$1.encode(UUIDUtil.java:50) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.core.UUIDUtil$1.encode(UUIDUtil.java:45) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.network.FriendlyByteBuf.writeCollection(FriendlyByteBuf.java:165) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.network.protocol.game.ClientboundPlayerInfoRemovePacket.write(ClientboundPlayerInfoRemovePacket.java:21) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.network.codec.StreamCodec$2.encode(StreamCodec.java:38) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:88) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:78) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	... 45 more
[16:22:39 ERROR]: #!#!     at PoaSK (2).jar//poa.poaskrewritev2.effects.entity.EffRemoveFakePlayer.execute(EffRemoveFakePlayer.java:46)
[16:22:39 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[16:22:39 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[16:22:39 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[16:22:39 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[16:22:39 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:316)
[16:22:39 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:275)
[16:22:39 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:286)
[16:22:39 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:221)
[16:22:39 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:22:39 ERROR]: #!#!     at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
[16:22:39 ERROR]: #!#!     at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[16:22:39 ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
[16:22:39 ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[16:22:39 ERROR]: #!#!     at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[16:22:39 ERROR]: #!#!     at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[16:22:39 ERROR]: #!#!     at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[16:22:39 ERROR]: #!#!     at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448)
[16:22:39 ERROR]: #!#!     at net.minecraft.commands.Commands.performCommand(Commands.java:355)
[16:22:39 ERROR]: #!#!     at net.minecraft.commands.Commands.performCommand(Commands.java:342)
[16:22:39 ERROR]: #!#!     at net.minecraft.commands.Commands.performCommand(Commands.java:337)
[16:22:39 ERROR]: #!#!     at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202)
[16:22:39 ERROR]: #!#!     at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176)
[16:22:39 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[16:22:39 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[16:22:39 ERROR]: #!#!     at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[16:22:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511)
[16:22:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195)
[16:22:39 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[16:22:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488)
[16:22:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411)
[16:22:39 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[16:22:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377)
[16:22:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238)
[16:22:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[16:22:39 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1570)
[16:22:39 ERROR]: #!#! 
[16:22:39 ERROR]: #!#! Version Information:
[16:22:39 ERROR]: #!#!   Skript: 2.8.6 (latest)
[16:22:39 ERROR]: #!#!     Flavor: skriptlang-github
[16:22:39 ERROR]: #!#!     Date: 15:29:23.319558700
[16:22:39 ERROR]: #!#!   Bukkit: 1.20.6-R0.1-SNAPSHOT
[16:22:39 ERROR]: #!#!   Minecraft: 1.20.6
[16:22:39 ERROR]: #!#!   Java: 22.0.1 (Java HotSpot(TM) 64-Bit Server VM 22.0.1+8-16)
[16:22:39 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[16:22:39 ERROR]: #!#! 
[16:22:39 ERROR]: #!#! Server platform: Paper
[16:22:39 ERROR]: #!#! 
[16:22:39 ERROR]: #!#! Current node: null
[16:22:39 ERROR]: #!#! Current item: spawn fake player
[16:22:39 ERROR]: #!#! Current trigger: command /spawnsleeper (simple event) (misc\sleepers.sk, line 11)
[16:22:39 ERROR]: #!#! 
[16:22:39 ERROR]: #!#! Thread: Server thread
[16:22:39 ERROR]: #!#! 
[16:22:39 ERROR]: #!#! Language: english
[16:22:39 ERROR]: #!#! Link parse mode: STRICT
[16:22:39 ERROR]: #!#! 
[16:22:39 ERROR]: #!#! End of Error.
[16:22:39 ERROR]: #!#! 
[16:22:39 INFO]: AmazinAxel lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:player_info_remove'
```

As an unrelated issue, it seems like setting the server brand does not work. When setting the server brand, it returns this error:


```
[16:22:42 ERROR]: #!#! 
[16:22:42 ERROR]: #!#! [Skript] Severe Error:
[16:22:42 ERROR]: #!#! 
[16:22:42 ERROR]: #!#! Something went horribly wrong with Skript.
[16:22:42 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:22:42 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[16:22:42 ERROR]: #!#! Here is full list of them:
[16:22:42 ERROR]: #!#! skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect) SkBee v3.5.1 (https://github.com/ShaneBeee/SkBee) 
[16:22:42 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[16:22:42 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[16:22:42 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[16:22:42 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[16:22:42 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[16:22:42 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[16:22:42 ERROR]: #!#! 
[16:22:42 ERROR]: #!#! Stack trace:
[16:22:42 ERROR]: #!#! java.lang.ClassCastException: class net.minecraft.network.protocol.common.custom.BrandPayload cannot be cast to class net.minecraft.network.protocol.Packet (net.minecraft.network.protocol.common.custom.BrandPayload and net.minecraft.network.protocol.Packet are in unnamed module of loader java.net.URLClassLoader @4dcbadb4)
[16:22:42 ERROR]: #!#!     at PoaSK (2).jar//poa.packets.SendPacket1206.sendPacket(SendPacket1206.java:9)
[16:22:42 ERROR]: #!#!     at PoaSK (2).jar//poa.packets.SendPayloadPacket1206.sendBrandPayload(SendPayloadPacket1206.java:24)
[16:22:42 ERROR]: #!#!     at PoaSK (2).jar//poa.packets.SendPayloadPacket.sendBrandPayload(SendPayloadPacket.java:27)
[16:22:42 ERROR]: #!#!     at PoaSK (2).jar//poa.poaskrewritev2.effects.EffBrand.execute(EffBrand.java:37)
[16:22:42 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[16:22:42 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[16:22:42 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[16:22:42 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[16:22:42 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.SkriptEventHandler.lambda$check$3(SkriptEventHandler.java:155)
[16:22:42 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.SkriptEventHandler.lambda$check$4(SkriptEventHandler.java:166)
[16:22:42 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.util.Task.callSync(Task.java:164)
[16:22:42 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.util.Task.callSync(Task.java:148)
[16:22:42 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:164)
[16:22:42 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[16:22:42 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:66)
[16:22:42 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[16:22:42 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:22:42 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[16:22:42 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[16:22:42 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627)
[16:22:42 ERROR]: #!#!     at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347)
[16:22:42 ERROR]: #!#!     at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:153)
[16:22:42 ERROR]: #!#!     at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22)
[16:22:42 ERROR]: #!#!     at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13)
[16:22:42 ERROR]: #!#!     at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55)
[16:22:42 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[16:22:42 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[16:22:42 ERROR]: #!#!     at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[16:22:42 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511)
[16:22:42 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195)
[16:22:42 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[16:22:42 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488)
[16:22:42 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411)
[16:22:42 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[16:22:42 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377)
[16:22:42 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238)
[16:22:42 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[16:22:42 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1570)
[16:22:42 ERROR]: #!#! 
[16:22:42 ERROR]: #!#! Version Information:
[16:22:42 ERROR]: #!#!   Skript: 2.8.6 (latest)
[16:22:42 ERROR]: #!#!     Flavor: skriptlang-github
[16:22:42 ERROR]: #!#!     Date: 15:29:23.319558700
[16:22:42 ERROR]: #!#!   Bukkit: 1.20.6-R0.1-SNAPSHOT
[16:22:42 ERROR]: #!#!   Minecraft: 1.20.6
[16:22:42 ERROR]: #!#!   Java: 22.0.1 (Java HotSpot(TM) 64-Bit Server VM 22.0.1+8-16)
[16:22:42 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[16:22:42 ERROR]: #!#! 
[16:22:42 ERROR]: #!#! Server platform: Paper
[16:22:42 ERROR]: #!#! 
[16:22:42 ERROR]: #!#! Current node: null
[16:22:42 ERROR]: #!#! Current item: set server brand to "Permafrost" for the player
[16:22:42 ERROR]: #!#! Current trigger: join (simple event) (join.sk, line 3)
[16:22:42 ERROR]: #!#! 
[16:22:42 ERROR]: #!#! Thread: Server thread
[16:22:42 ERROR]: #!#! 
[16:22:42 ERROR]: #!#! Language: english
[16:22:42 ERROR]: #!#! Link parse mode: STRICT
[16:22:42 ERROR]: #!#! 
[16:22:42 ERROR]: #!#! End of Error.
[16:22:42 ERROR]: #!#! 
```

Let me know if i should make a new issue for this other problem

**Comment by AmazinAxel** [comment]
It should be noted that the last two updates (regarding metadata packets and skin layers) did not fix the problem.
here's my /sk info if it helps:
![image](https://github.com/Ekpoa/PoaSkRewritev2/assets/87440159/e0876215-b8e9-4ade-b737-1a3d53bb3549)

**Comment by Ekpoa** [comment]
ok so i have updated it: https://www.spigotmc.org/resources/poask-skript-addon.104512/

the syntax's have changed for spawning and removing. Getting the id of the entity has been removed.

https://skripthub.net/docs/?id=11219

a good example has been on this doc. Also brand payload should be fixed too now :D

**Comment by AmazinAxel** [comment]
thanks for the update!! the brand syntax works perfectly now, and so does spawning a fake player. I now have this code:

```vb
command /spawnSleeper:
    trigger:

        set {_id} to 100000 # Hardcoded ID for debugging
        set {_uuid} to a random uuid

        remove fake player with id {_id} and uuid {_uuid} for all players

        spawn fake player named player's name with skin named player's name on tablist false at player for all players with id {_id} and uuid {_uuid}

        send metadata packet with uuid {_uuid} pose "sleeping" to all players
```
The only issue remaining now is sending the metadata packet, as currently it is not making the fake player change its pose.
in the console after running the command, the only error is `'[PoaSkRewritev2] No entity exists with that UUID. If it is a fake entity use the entity id'`

i set the UUID as a variable, so the same uuid is being used for both the spawn and metadata packet send request. Waiting a few ticks after spawning does not fix it either. using any other metadata packets such as hiding the fake player's name does not work either.

Thank you for the update :D

**Comment by AmazinAxel** [comment]
Also in the docs, an incorrect example is given for the [spawn fake player effect](https://skripthub.net/docs/?id=11219)
there must be a location declared every time a fake player is spawned but the example doesn't declare the location
so the example `spawn fake player named "bob" for all players with id {_id} and uuid {_uuid}` should be `spawn fake player named "bob" **at player** for all players with id {_id} and uuid {_uuid}`
just a minor nitpick but it might confuse some other people who are wondering why the example doesn't work

**Comment by Ekpoa** [comment]
use the metadata building one, its far more effective and customizable. the other one is outdated

`set {_m} to metadata packet with id {_id}
add data from "pose sleeping" to {_m}

send packet {_m} to all players`

**Comment by AmazinAxel** [comment]
issue resolved 👍 
the other metadata packet effect should be deprecated or removed
this method works now!

**Comment by AmazinAxel** [comment]
technically this issue isn't fully resolved because the packet is sent to all players, which crashes players if there are multiple online (see skunity discord: https://discord.com/channels/135877399391764480/1248294302967398471/1248353971236634706)
